/**
 * Purpose: Convert persisted Custom Node definitions into registry NodeDefinition entries.
 */
import type { CustomNodeDefinition } from './semantic-graph-types.js';
import type { NodeDefinition, NodePort, PortType } from './types.js';

export const CUSTOM_NODE_TYPE_PREFIX = 'custom:' as const;

export function customNodeType(definitionId: string): string {
  return `${CUSTOM_NODE_TYPE_PREFIX}${String(definitionId ?? '')}`;
}

const normalizePortType = (value: unknown): PortType => {
  const type = String(value ?? 'any') as PortType;
  const allowed: PortType[] = [
    'number',
    'boolean',
    'string',
    'asset',
    'color',
    'audio',
    'image',
    'video',
    'scene',
    'effect',
    'client',
    'command',
    'fuzzy',
    'array',
    'any',
  ];
  return allowed.includes(type) ? type : 'any';
};

const portFromCustomPort = (port: CustomNodeDefinition['ports'][number]): NodePort => ({
  id: String(port.portKey ?? ''),
  label: String(port.label ?? port.portKey ?? ''),
  type: normalizePortType(port.type),
});

export function createCustomNodeDefinitionNode(definition: CustomNodeDefinition): NodeDefinition {
  const inputs = (definition.ports ?? [])
    .filter((port) => port.side === 'input' && port.portKey)
    .map(portFromCustomPort);
  const outputs = (definition.ports ?? [])
    .filter((port) => port.side === 'output' && port.portKey)
    .map(portFromCustomPort);

  return {
    type: customNodeType(definition.definitionId),
    label: String(definition.name ?? 'Custom Node'),
    category: 'Custom',
    metadata: {
      version: '1.0.0',
      platformTargets: ['manager', 'client', 'display'],
      sideEffectClass: 'local-state',
      permissions: ['graph:state'],
      compatibility: [],
      examples: [],
      risks: [],
      description: `${String(definition.name ?? 'Custom Node')} custom node generated by Nodelization.`,
      repairHints: ['Inspect the original Custom Node definition when inferred ports do not match intent.'],
    },
    inputs,
    outputs,
    configSchema: [],
    process: () => ({}),
  };
}
